### ISSUE TITLE
Any plans to support native MacOS builds?

### ISSUE THREAD

**Issue by cjhoward92** [appoptics/appoptics-bindings-node#102]
Right now the package (and therefore [appoptics-apm-node](https://github.com/appoptics/appoptics-apm-node)) only support linux. This is mostly fine (our production env is all linux) but it would make testing easier if MacOS was supported. Are there any plans to support MacOS or is Linux a limitation of liboboe?

**Comment by ronilan** [comment]
The pain is understood, but his is not going the happen. If anything, and this is also very unlikely, platform independency will be achieved by removing the dependency on the bindings altogether.

All development of both packages is currently done on Mac inside docker containers. You can find the configuration inside the `dev` directory of both repos. It might, maybe, help a little.

Sorry.
