### ISSUE TITLE
the agent not working with .net core alpine images

### ISSUE THREAD

**Issue by jasonliao-cb** [appoptics/appoptics-bindings-node#121]
Hi, we thought the agent supports Alpine images before the Alpine 3.14
[Supported Platforms # Linux](https://documentation.solarwinds.com/en/success_center/appoptics/content/kb/apm_tracing/supported_platforms.htm#link3)

When we test the .net core 3.1 Alpine and .net 6.0 Alpine, non of the images can collect any data. A list as below:

3.1-alpine3.16 not work
3.1-focal work
6.0-alpine3.15 not work
6.0-alpine3.14 not work
6.0-focal work
6.0 work

[ASP.NET Core Runtime # Linux amd64 Tags](https://hub.docker.com/_/microsoft-dotnet-aspnet)

which package is required to make it work in Alpine?

**Comment by ronilan** [comment]
@jasonliao-cb - this repo is for the Node.js bindings a dependency of the Node agent (which works on alpine)

For dot Net and other platforms support requests, please email [technicalsupport@solarwinds.com](mailto:technicalsupport@solarwinds.com)
