### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by mbackonja** [appoptics/appoptics-bindings-node#128]
Hello everyone!

I encountered problems when trying to install the `appoptics-apm` npm package on both a t4g AWS EC2 instance with ARM architecture and a Macbook M2. The error message was related to `MODULE_NOT_FOUND`, and upon further investigation, I discovered that the package was trying to load `@appoptics/apm-bindings`, but the required `liboboe` library was not present on the operating system. Further analysis showed that `@appoptics/apm-bindings` only includes x86 and alpine versions of the library, but an aarch64 version can be found on https://files.appoptics.com/c-lib/. I have submitted a PR to include the aarch64 version on systems with ARM64 architecture and it is working as expected on t4g EC2 instances.

PR: https://github.com/appoptics/appoptics-bindings-node/pull/127

**Comment by cheempz** [comment]
Hi @mbackonja thank you for the investigation and PR!  I think you might be compiling the extension from source which the PR changes would make work.  But the full build process for this package, where we currently use `node-pre-gyp` to support precompiled binaries, has issues with the ARM architecture and long story short, we are (or rather @raphael-theriault-swi is) busily working on a revamp to the build and distribution process for the next-gen product SolarWinds Observability, see https://github.com/solarwindscloud/solarwinds-apm-node and https://github.com/solarwindscloud/solarwinds-bindings-node.

It would be ideal if you/your organization can migrate to SolarWinds Observability but if that isn't an option, the `solarwinds-apm` package can be configured to report to the AppOptics platform.  Please drop me a note at lin.lin@solarwinds.com with information about your AppOptics account and we can take it from there!

**Comment by raphael-theriault-swi** [comment]
Closing this as arm64 Linux support is available in `solarwinds-apm` as s drop-in replacement and there are no plans to support macOS
